In [1]:
import pandas as pd

# Read in the data
df = pd.read_csv('scores.csv')

df

,Treebank,Encoding,Language Model,In training data,Random,Task,UAS,LAS,CLAS,MLAS,BLEX,POS,1-deptag,Arc,1-plane,2-plane,Deprel
0,UD_Guajajara-TuDeT,rel-pos,bert-base-multilingual-cased,False,False,single,47.06,23.53,15.65,1.17,0.0,64.05,45.88,NaN,NaN,NaN,NaN
1,UD_Guajajara-TuDeT,rel-pos,bert-base-multilingual-cased,False,True,multi,45.71,29.58,25.06,2.63,0.0,64.18,NaN,60.92,NaN,NaN,60.92
2,UD_Guajajara-TuDeT,rel-pos,bert-base-multilingual-cased,False,True,single,47.73,23.87,15.32,1.58,0.0,65.23,44.58,NaN,NaN,NaN,NaN
3,UD_Guajajara-TuDeT,rel-pos,bert-base-multilingual-cased,False,False,multi,42.02,24.87,22.17,1.93,0.0,63.92,NaN,55.95,NaN,NaN,61.83
4,UD_Guajajara-TuDeT,rel-pos,xlm-roberta-base,False,True,single,47.39,25.04,15.60,1.15,0.0,65.10,44.05,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,UD_English-EWT,rel-pos,bert-base-cased,True,False,multi,67.42,60.35,55.96,6.48,0.0,95.10,NaN,68.48,NaN,NaN,85.38
391,UD_English-EWT,relative,bert-base-cased,True,False,single,53.58,49.14,48.26,5.12,0.0,95.09,57.44,NaN,NaN,NaN,NaN
392,UD_English-EWT,relative,bert-base-cased,True,False,multi,47.45,42.37,41.20,3.99,0.0,95.14,NaN,54.90,NaN,NaN,85.37
393,modelo finetuneado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,UD_Ligurian-GLT,2-planar-brackets-greedy,dbmdz/bert-base-italian-cased,1,False,multi,67.80,59.79,50.53,10.34,0.0,91.95,NaN,NaN,71.24,100.0,82.59

In [2]:
import sklearn

In [78]:
rel_pos = df[df['Encoding'] == 'rel-pos'][df['Language Model'] == 'xlm-roberta-base'][df['Task'] == 'multi']
rel_pos = rel_pos.drop(['Language Model', 'Encoding', 'Task', 'BLEX'], axis=1).dropna(axis=1).sort_values(['Treebank', 'Random'], ascending=False)

rel_pos = rel_pos.set_index(['Treebank', 'Random'])#.groupby(level=0).diff().dropna().reset_index().drop('Random', axis=1)

#rel_pos['In training data'] = [True, True, True, False, False, False, False, True, False, True, True, False]

rel_pos

/home/alberto/anaconda3/envs/ml_probing/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

                                 In training data    UAS    LAS   CLAS   MLAS  \
Treebank                 Random
UD_Welsh-CCG             True                True  45.99  24.35  15.08   0.50
                         False               True  56.18  32.13  19.74   0.25
UD_Vietnamese-VTB        True                True  23.89  13.87  10.01   4.84
                         False               True  39.38  27.48  25.58  16.34
UD_Turkish-BOUN          True                True  27.95  15.67   9.84   1.59
                         False               True  56.26  45.56  42.59   5.56
UD_Skolt_Sami-Giellagas  True               False  29.28   8.23   8.06   0.00
                         False              False   6.75   3.10   2.76   0.00
UD_Ligurian-GLT          True               False  18.38  10.03   5.62   1.12
                         False              False  24.57   3.17   0.83   0.00
UD_Kiche-IU              True               False  47.12  34.75  22.85   4.16
                         False              False  45.68  27.75  15.18   0.97
UD_Guajajara-TuDeT       True               False  45.71  28.91  25.16   2.29
                         False              False  40.17  19.66  18.05   1.43
UD_Bulgarian-BTB         True                True  30.24  21.60  11.72   0.16
                         False               True  69.63  59.06  53.00   0.48
UD_Bhojpuri-BHTB         True               False  17.41  11.98   5.21   0.14
                         False              False  31.79   4.85   3.73   0.12
UD_Basque-BDT            True                True  25.06  16.15  12.12   0.95
                         False               True  54.78  43.29  40.70   5.53
UD_Armenian-ArmTDP       True                True  22.94  11.98   9.03   0.25
                         False               True  51.61  38.08  31.58   1.80
UD_Ancient_Greek-Perseus True               False  25.90  16.25   7.94   0.96
                         False              False  41.37  28.46  20.23   2.21

                                   POS    Arc  Deprel
Treebank                 Random
UD_Welsh-CCG             True    63.55  54.14   48.29
                         False   67.33  54.18   51.96
UD_Vietnamese-VTB        True    66.12  41.39   49.40
                         False   74.64  49.15   59.43
UD_Turkish-BOUN          True    66.03  44.16   52.86
                         False   86.07  57.01   74.40
UD_Skolt_Sami-Giellagas  True    48.43  40.42   37.75
                         False   38.56  15.21   31.13
UD_Ligurian-GLT          True    50.26  34.17   42.04
                         False   39.05  25.59   12.01
UD_Kiche-IU              True    73.49  63.82   65.25
                         False   64.94  58.30   56.54
UD_Guajajara-TuDeT       True    66.27  60.00   58.82
                         False   57.52  42.35   41.44
UD_Bulgarian-BTB         True    70.71  48.76   61.33
                         False   96.70  69.51   80.80
UD_Bhojpuri-BHTB         True    51.20  39.10   45.22
                         False   41.25  26.91   27.87
UD_Basque-BDT            True    65.56  45.30   55.34
                         False   85.74  59.35   73.16
UD_Armenian-ArmTDP       True    62.44  40.56   51.26
                         False   78.92  51.87   67.70
UD_Ancient_Greek-Perseus True    63.29  39.18   53.98
                         False   78.34  47.40   65.26

In [76]:
rel_pos = df[df['Encoding'] == 'absolute'][df['Language Model'] == 'xlm-roberta-base'][df['Task'] == 'single']
rel_pos = rel_pos.drop(['Language Model', 'Encoding', 'Task', 'BLEX'], axis=1).dropna(axis=1).sort_values(['Treebank', 'Random'], ascending=False)

rel_pos = rel_pos.set_index(['Treebank', 'Random'])#.groupby(level=0).diff().dropna().reset_index().drop('Random', axis=1)

#rel_pos['In training data'] = [True, True, True, False, False, False, False, True, False, True, True, False]

rel_pos

/home/alberto/anaconda3/envs/ml_probing/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

                                 In training data    UAS    LAS   CLAS  MLAS  \
Treebank                 Random
UD_Welsh-CCG             True                True  12.49   6.20   7.56  0.75
                         False               True  11.04   4.82   4.03  0.17
UD_Vietnamese-VTB        True                True   9.76   4.42   3.15  1.35
                         False               True   6.97   1.97   1.15  0.77
UD_Turkish-BOUN          True                True   7.00   3.36   2.40  0.34
                         False               True   5.86   3.32   2.75  0.63
UD_Skolt_Sami-Giellagas  True               False   9.04   2.83   3.75  0.00
                         False              False   5.26   3.51   4.57  0.00
UD_Ligurian-GLT          True               False   5.76   1.39   1.90  0.00
                         False              False   2.83   1.30   1.75  0.00
UD_Kiche-IU              True               False  32.30  20.55  17.82  1.54
                         False              False  26.77  14.82  10.48  0.19
UD_Guajajara-TuDeT       True               False  42.69  17.65  15.26  0.79
                         False              False  38.82  14.45  15.87  1.02
UD_Bulgarian-BTB         True                True  11.58   6.70   5.07  0.13
                         False               True  13.11   8.13   6.99  0.16
UD_Bhojpuri-BHTB         True               False   4.95   1.54   1.34  0.00
                         False              False   1.33   0.27   0.32  0.00
UD_Basque-BDT            True                True   8.59   4.04   3.00  0.22
                         False               True   7.53   3.81   3.05  0.29
UD_Armenian-ArmTDP       True                True   7.05   2.88   2.29  0.06
                         False               True   5.59   1.94   1.47  0.00
UD_Ancient_Greek-Perseus True               False  11.20   5.34   3.72  0.57
                         False              False  11.82   5.62   4.17  0.66

                                   POS  1-deptag
Treebank                 Random
UD_Welsh-CCG             True    63.85     19.13
                         False   66.39     17.41
UD_Vietnamese-VTB        True    66.26     20.58
                         False   74.93     18.83
UD_Turkish-BOUN          True    66.08     25.89
                         False   86.15     25.10
UD_Skolt_Sami-Giellagas  True    46.23     19.63
                         False   35.42      2.56
UD_Ligurian-GLT          True    50.13     11.48
                         False   37.95      0.88
UD_Kiche-IU              True    73.21     45.33
                         False   65.47     39.12
UD_Guajajara-TuDeT       True    63.53     39.61
                         False   33.07     16.34
UD_Bulgarian-BTB         True    70.71     25.60
                         False   96.65     25.52
UD_Bhojpuri-BHTB         True    49.90     16.49
                         False   42.50      1.24
UD_Basque-BDT            True    65.60     23.20
                         False   85.89     23.06
UD_Armenian-ArmTDP       True    62.67     17.14
                         False   78.98     15.78
UD_Ancient_Greek-Perseus True    63.25     22.10
                         False   78.43     20.75